#1 RANDOM USER
from random import randint
def randomUserID():
    print(randint(100000,900000))
idGenerated=randomUserID()
print(idGenerated)

#2 USER GENERATED BY USER
import random
import string
def userByUser(nu,car):
    numeros=''.join(random.choices(string.digits, k=nu))
    letras=''.join(random.choices(string.ascii_letters, k=car))
    idFinal=numeros+letras
    return''.join(random.sample(idFinal,len(idFinal)))
car=int(input('Type the number of the characters you want: '))
nu=int(input('Type the number of the numbers you want: '))
idGenerado=userByUser(nu,car)
print(f'ID generado: {idGenerado}')

#3 COLORS
import random
def rgbColorGen():
    return f'The color is: {(random.randint(0,255),random.randint(0,255),random.randint(0,255))}'
print(rgbColorGen())

#4 HEXA COLORS
import random
def hexaColors(hex):
    hexC=['#'+''.join(random.choices('012346789abcdef',k=6))for _ in range(hex)]
    return hexC
print(hexaColors(3))

#5 LIST OF RGB COLORS
import random
def listOfRgbColors(rgb):
    rgbCol=[f'rgb({random.randint(0,255)},{random.randint(0,255)},{random.randint(0,255)})'for _ in range(rgb)]
    return rgbCol
print(listOfRgbColors(3))

#6 GENERATE HEXA OR RGB COLORS
def generateColors(colorType,v):
    if colorType=='hexa':
        return hexaColors(v)
    elif colorType=='rgb':
        return listOfRgbColors(v)
    else:
        return "tipo de color no válido. Usa 'hexa' o 'rgb'."
print(generateColors('hexa',6))
print(generateColors('rgb',6))

#7 SHUFFLE LIST
import random
def shuffleList(list):
    random.shuffle(list)
    return list
print(shuffleList([22,23,24,25,26,27,28]))

#8 UNIQUE RANDOM NUMBERS
import random
def uniqueRandomNumbers():
    return random.sample(range(10),7)
print(uniqueRandomNumbers())