#1 RANDOM USER
from random import randint
def randomUserID():
    print(randint(100000,900000))
idGenerated=randomUserID()
print(idGenerated)

#2 USER GENERATED BY USER
import random
import string
def userByUser(nu,car):
    numeros=''.join(random.choices(string.digits, k=nu))
    letras=''.join(random.choices(string.ascii_letters, k=car))
    idFinal=numeros+letras
    return''.join(random.sample(idFinal,len(idFinal)))
car=int(input('Type the number of the characters you want: '))
nu=int(input('Type the number of the numbers you want: '))
idGenerado=userByUser(nu,car)
print(f'ID generado: {idGenerado}')

#3 COLORS
red=85
green=170
blue=255
#def rgbColorGen():